### ISSUE TITLE
Assessment 1

### ISSUE THREAD

**Issue by rizzamandasari** [Zrlysaa/booksrulesapp#1]
Aplikasi berjalan dengan baik, namun fitur bahasa tidak ada.
Ada perubahan aplikasi di Assessment selanjutnya ya? Sebaiknya untuk memudahkan dibuat branch disetiap assessmentnya.

**Comment by Zrlysaa** [comment]
baik ibu Terimakasih 🙏🏻 , Maaf ibu Aplikasi saya memiliki kekurangan,
sepertinya saya telah menambahkan kodingan untuk 2 bahasa tapi mungkin ada
suatu kesalahan pada saya, Apakah perlu ada perbaikan ya ibu? , Maaf mengganggu waktunya ibu 🙏🏻

Pada Sab, 22 Jun 2024 pukul 23.29 Rizza Mandasari ***@***.***>
menulis:

**Comment by Zrlysaa** [comment]
Maaf ibu, untuk file yang Asesment 1 nya kebetulan sudah terupdate dengan yang Asesment 2 ibu, Saya ijin menambahkan fitur Bahasanya pada Asesment 2 ibu 🙏🏻, kemudian akan saya branch kembali dengan  Asesment 2 ibu

**Comment by rizzamandasari** [comment]
ok

**Comment by Zrlysaa** [comment]
> ok

Terimakasih ibu 🙏🏻
